version: '3.8'
services:
  redis:
    container_name: redis-test
    image: redislabs/redistimeseries:latest
    ports:
      - '6379:6379'
    # command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data

  # grafana:
  #   container_name: grafana
  #   image: ghcr.io/redisgrafana/redis-app:latest
  #   ports:
  #     - "3000:3000"
  #   user: "1001"
  #   environment:
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_BASIC_ENABLED=false
  #     - GF_ENABLE_GZIP=true
  #     - GF_USERS_DEFAULT_THEME=dark
  #   volumes:
  #     - ./provisioning:/etc/grafana/provisioning
  #     - ./dashboards:/etc/dashboards
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  
  populate:
    container_name: populate
    image: populate:0.1
    depends_on:
      - redis
    links:
      - redis
    build: ./QuotePopulate/

volumes:
  cache:
    driver: local
